name: Auto Pull
on:
  push:
    branches: [ "main" ]

jobs:
  sync-code:
    runs-on: self-hosted
    steps:
      - name: Pull latest code
        run: |
          cd ~/projects/docker
          git pull origin main
          # 在構建前校準時間，避免編譯錯誤
          sudo hwclock -s
